# Generated by Django 5.2.3 on 2025-06-14 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du département')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du poste')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire')),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme'), ('A', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='Employes.department', verbose_name='Département')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='Employes.poste', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
    ]
