# Generated by Django 5.2.3 on 2025-11-22 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employes.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
            },
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('motif', models.CharField(max_length=200, verbose_name='Motif de la prime')),
                ('date_attribution', models.DateField(auto_now_add=True, verbose_name="Date d'attribution")),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employes.employee', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
    ]
